# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a2f2590c36e50be3026f35441c6042cdcb6ef552323e9db5f9f610a4e47a94830f7fc0b0499615b7439be34282f91da5d983619bd4fcdb9b2b5264e21d36d8

test:
  secret_key_base: b50d25d828578ddbd081ccd5dd8ca2a1566cf26e0838dcdfed5d3685b8c3b00dbcb519feaf6cb6ac5d6bb2d4495facbd29b8166d5e94df9179d898b9571184b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
